name: Managing Secrets
on:
    workflow_dispatch: 
    push:
jobs:
    print_repo_secrets:
        runs-on: ubuntu-latest
        steps:
            - name: Read Repository Masked Secret
              run: echo ${{ secrets.dev_api_key }}

            - name: Read Repository Secret Content
              run: echo ${{ secrets.dev_api_key }} | sed 's/./& /g'

            - name: Read PRODUCTION Secret Content
              run: echo ${{ secrets.prod_api_key }} | sed 's/./& /g'
    
    print_environment_secrets:
        environment: production
        runs-on: ubuntu-latest
        steps:
            - name: Read DEV_API_KEY Repository Secret Content
              run: echo ${{ secrets.dev_api_key }} | sed 's/./& /g'

            - name: Read PROD_API_KEY PRODUCTION Secret Content
              run: echo ${{ secrets.prod_api_key }} | sed 's/./& /g'
